---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "operator-manual-kubecon-deep-dive-terraform-and-kubernetes"
spec:
  organization: hashicorp-team-demo
  secretsMountPath: "/tmp/secrets"
  module:
    source: "joatmon08/hello/random"
    version: "5.0.0"
  outputs:
    - key: pet
      moduleOutputName: pet
    - key: list_of_pets
      moduleOutputName: list_of_pets
    - key: quoted_some_key
      moduleOutputName: quoted_some_key
  variables:
    - key: hellos
      value: |
        {
          hello="KubeCon"
          second_hello="North America"
        }
      hcl: true
      sensitive: false
      environmentVariable: false
    - key: some_key
      sensitive: false
      value: '"something"'
      environmentVariable: false
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true
