apiVersion: v1
kind: Service
metadata:
  name: beacon-yaml
  namespace: beacon-yaml
spec:
  selector:
    app: beacon-yaml
  ports:
    - port: 8081
      targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer
